### ISSUE TITLE
Migrate to the androidx package structure

### ISSUE THREAD

**Issue by jonduran3000** [Rightpoint/android-template#24]
See: https://developer.android.com/topic/libraries/support-library/androidx-overview

**Comment by sbilling** [comment]
@jonduran3000 is this something we want to wait on? Was just reading through the documentation and it looks like it is still in alpha. @octohub be sure to weigh in if you have some thoughts.

**Comment by octohub** [comment]
@sbilling @jonduran3000 The AndroidX namespace is now stable so there should be no issues migrating to it: https://developer.android.com/topic/libraries/support-library/androidx-rn?linkId=57203177

**Comment by octohub** [comment]
Done
