### ISSUE TITLE
MVI Sample Project

### ISSUE THREAD

**Issue by jonduran3000** [Rightpoint/android-template#3]
Sample app to show an opinionated architecture built on top of the android-template.

Specs:

* List all Raizlabs repos: https://api.github.com/orgs/raizlabs/repos
* Clicking a repo opens a detail view which displays:
  * The latest commit: https://api.github.com/repos/Raizlabs/RZUtils/commits
  * The number of open issues: https://api.github.com/repos/Raizlabs/android-template/issues
* List of repos should fetch from db first, and if the data is older than 5 minutes, fetch from the network, update the db and the ui with the response.
* For latest commit and open issues, if the data from the db is older than 10 minutes, fetch from the network, update the db and the ui with the response.
* Include a README.MD file explaining the architecture providing blog posts / resources for devs to learn more.

**Comment by octohub** [comment]
Progress has been made on this with the following PR: https://github.com/Raizlabs/android-template/pull/20.

Leaving this issue as open until it has been completed.

**Comment by jonduran3000** [comment]
I believe we now have a solid MVI example that handles the above criteria as merging #52.  Closing this issue.
