### ISSUE TITLE
Expand on contribution section

### ISSUE THREAD

**Issue by sbilling** [Rightpoint/android-template#31]
The contributing section of the readme should highlight best practices for making changes to the template i.e. directions for something as simple as checking out the repo, making a change, confirming it builds and committing it. Some changes require file regeneration and some do not - an explanation in the contribution section of ways in which to contribute would be very helpful.

**Comment by octohub** [comment]
[Contributing](https://github.com/Raizlabs/android-template/blob/develop/contributing.md) section has been updated.
