### ISSUE TITLE
Use relative links to refer to the internal project files on README

### ISSUE THREAD

**Issue by Ibrahimhassan1** [Rightpoint/android-template#36]
Use relative links to refer to the internal project files so that the repository README works offline.
Examples for links: [dependencies.gradle](https://github.com/Raizlabs/android-template/blob/develop/%7B%7B%20cookiecutter.repo_name%20%7D%7D/gradle/dependencies.gradle) can be changed to [dependencies.gradle](./android-template/{{ cookiecutter.repo_name }}/gradle/dependencies.gradle)

**Comment by octohub** [comment]
Done.
