### ISSUE TITLE
Add step on CircleCi to generate project

### ISSUE THREAD

**Issue by octohub** [Rightpoint/android-template#39]
To confirm the template is generating a compilable project, add a step to generate a project using the latest changes to the `android-template`.

**Comment by k-thryn** [comment]
Hi @octohub! Would this involve steps different from what is in [ci_script](https://github.com/Raizlabs/android-template/blob/develop/ci_script.sh)? It looks like this may already be happening.

**Comment by octohub** [comment]
@k-thryn Great point. I think you are correct. Can you chime in @jonduran3000?

**Comment by jonduran3000** [comment]
@octohub Yes this is part of the CI build.  If you push up any changes it should be generating a project and attempting to compile.
