### ISSUE TITLE
Add Android Studio scheme file that matches `checkstyle` test in CircleCI

### ISSUE THREAD

**Issue by colejd** [Rightpoint/android-template#51]
Is it feasible to have a [scheme file](https://metova.com/how-to-import-the-official-android-code-style/) that matches the linting tests we automatically run on Circle? I'm not sure what specific rules we're using there, but it would be great to let the IDE catch issues instead of waiting several minutes after pushing a commit for the tests to fail in order to fix things.

**Comment by jonduran3000** [comment]
@colejd You can refer to this: https://github.com/shyiko/ktlint#-with-intellij-idea

Also, all these commands are available via the command line so if you want to run the checks, the formatter or any of the other ktlint tools locally you can do so using Gradle.

**Comment by jonduran3000** [comment]
As far as the rules we are using the [official Android Kotlin style guide](https://developer.android.com/kotlin/style-guide).

**Comment by colejd** [comment]
Okay, interesting! Thank you. There's a [method outlined in ktlint's readme](https://github.com/shyiko/ktlint#option-1-recommended) for configuring Android Studio's build-in formatter to produce ktlint-compatible code. Is this part of the template?

**Comment by jonduran3000** [comment]
Late to respond to this but I think it's certainly something we can add.
